### ISSUE TITLE
Blank page after submitting Invoice

### ISSUE THREAD

**Issue by vikram-bodige** [Equotix/Logic-Invoice#37]
Hi,
when i am creating an invoice and click on save, the response is blank. Can you please tell me what might be the issue.
![image](https://cloud.githubusercontent.com/assets/22408766/25575617/9fa84dfa-2e76-11e7-9bb3-0e3b6f51c944.png)

**Comment by EsmondTan** [comment]
@vikram-bodige Check the error logs for any errors you're getting. Do ensure you are using a clean copy of the software downloaded from our download link, and not from out git repo as it is the newest version in development.

If you have further issues regarding the discussion, do open a forum topic instead of using git.
