### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by obteo** [Equotix/Logic-Invoice#9]
Hello,

the mails i get are wrong and links dont work :/

[{Pro Clan servers}] New Recurring Payment #{1}
Hi {Matteo},
Recurring payment #{1} was recently added to your account with the following details:
Cycle: {Quarterly}
Status: {Enabled}
Recurring Payment ID: {1}
Total: {€40.00}
Date Added: {03/09/2015}
Date Due: {12/11/2015}
You can view all your recurring payments by clicking here.
Regards,
{Pro Clan servers}

any idea please?

thank you.

**Comment by EsmondTan** [comment]
Perhaps you wish to try looking into the email template through the code editor. The issue may lie there.

**Comment by blmg911** [comment]
This is correct, 

The { } are not removed in the search and replace; If you remove them using the code editor yes this will work; However this is bad practice: {variable_insert} should be used instead of plain text such as variable_insert. 

The link does not work, this is actually an issue with the mail class and html emails.

**Comment by EsmondTan** [comment]
Fixed here: 96ab194174458a4f621e0d077f6abf25ae451cb5

**Comment by obteo** [comment]
i have not this URL: upload/admin/controller/accounting/

I'm using your latest version please use the brain b4 post or ppl get crazy and won't solve any problem. Cannot find the files you mentioned in the fix because the structure is different.

Date: Fri, 25 Dec 2015 21:47:24 -0800
